### ISSUE TITLE
handle informal yes/no responses

### ISSUE THREAD

**Issue by derekeder** [datamade/coordinated-entry-screening#15]
When asking a yes/no, phrase it like this:

`Are you cool? Reply Yes or No`

And accept the following responses (case insensitive):

* Yes: y yep yes yah yeah
* No: n nope no nah

**Comment by reginafcompton** [comment]
I've added "Type 'y' or 'n'" after YES/NO questions. The app is case insensitive, so "y" and "Y" both work.
