### ISSUE TITLE
confusing question on financial support

### ISSUE THREAD

**Issue by derekeder** [datamade/coordinated-entry-screening#16]
I had a hard time parsing this question. Is it two questions? 

`Do you have an income and require short term financial support?`

If I say yes, am I saying yes to both or to either?

**Comment by reginafcompton** [comment]
I think it might make more sense if we use "but" rather than "and." I'll discuss with the client.

**Comment by reginafcompton** [comment]
Answering "yes" to this question leads to the ["Homelessness Prevention Call Center."](http://www.catholiccharities.net/Portals/0/Programs%20and%20Services/Homelessness/Documents/HomelessPreventionCallCenter_FS_110816.pdf?ver=2017-01-31-130321-043) This resource can provide up to $2,500 to households that need a finite amount of financial assistance to avoid homelessness in times of crisis. The user must have an income to qualify.

Per our conversation with the client, we plan to reword the question with examples:

"Do you have an income, but require short term financial support to help with housing costs, e.g. rent, electric or heating bills, etc.?"

**Comment by reginafcompton** [comment]
Made this change in the [shared Google sheet](https://docs.google.com/spreadsheets/d/1e5pDtbK0BA_VdznwZggPLlOp9Z9VgpeIowayWDMGYgo/edit#gid=2043863495) and on the CES staging site.
