### ISSUE TITLE
Instruct how to respond to parentheticals

### ISSUE THREAD

**Issue by beamalsky** [datamade/coordinated-entry-screening#22]
I think a sentence at the beginning about what responses the app will accept would be extremely helpful. Something like:

> Choose your responses to these questions by texting back one of the options inside the parentheses.

User testing will be key here, but I can see this being non-intuitive. Would it be possible to accept the text on some answers? Here's a situation we'd want to avoid:

![img_4081](https://user-images.githubusercontent.com/1094243/44684189-0d0cb200-aa0e-11e8-85fa-62c7cf1d4ccc.PNG)

**Comment by reginafcompton** [comment]
I've added "Type 1, 2, 3, or 4" (or something along those lines) after every question. Closing this issue.
