### ISSUE TITLE
It takes too long to receive a message

### ISSUE THREAD

**Issue by reginafcompton** [datamade/coordinated-entry-screening#23]
Receiving a response can take several seconds. That's not okay. Determine where things get slow in the code, perhaps by enlisting the help of a [profiling](https://docs.python.org/3/library/profile.html#module-cProfile) [tool](https://github.com/rkern/line_profiler).

**Comment by reginafcompton** [comment]
**Approach**

*Strategy one* I attempted to set-up profiling using the django-debug-toolbar (which comes with a handy [line profiler](https://github.com/dmclain/django-debug-toolbar-line-profiler) that can even intercept redirects!). Unfortunately, capturing the POST request send from a cell phone proved to be rather difficult. I set up a view to do accomplish this: https://github.com/datamade/coordinated-entry-screening/pull/27. But Twilio would not validate the form (even when populating [it complete body data](https://github.com/datamade/rapidsms-twilio/blob/master/rtwilio/views.py#L33)) where the `twilio-backend` gets called and not requiring a signature). (I kept seeing a "form could not be validated" error.) In the end, I could not get the line profiler to show results in my browser.

*Strategy two* I walked through code with PDB, and it became clear that the delay begins within `rapdisms`, when calling `send` on the backend object: https://github.com/datamade/rapidsms/blob/master/rapidsms/router/blocking/router.py#L282

I used `profile` within the pdb shell, only to discover that the subsequent chain of functions all require a little time to run, i.e., I could not identify a smoking gun code block that causes the delay in sending the message. 

Not sure about next steps.

**Comment by reginafcompton** [comment]
**Debriefing and next steps**

This issue took us into the bowels of Twilio! 

I was able to set-up profiling using [the pattern given here](https://docs.python.org/3.5/library/profile.html#profile.Profile) - n.b. for Python 3.5. 
https://github.com/datamade/rapidsms/pull/2/files#diff-15e828e7d0db5f0c12cf70818c0adf13R290

The profiling results consistently showed that ...

**Comment by fgregg** [comment]
Are we really spending 2-3 seconds in our app? That's more than I would have expected.

I would recommend reaching out mRelief next.

**Comment by reginafcompton** [comment]
Why mRelief?

**Comment by reginafcompton** [comment]
I'll check those numbers.

**Comment by reginafcompton** [comment]
I spoke with Genevieve from mRelief. A couple points emerged from our conversation:

* we should consider using two or three Twilio phone numbers, but not use co-pilot (since it's an expensive service - I'll confirm with a Twilio sale rep). 
    * PRO: multiple numbers might prevent long wait times for messages. 
    * CON: we might now have more than one user on the tool at a time, meaning that the extra cost is not justifiable.
    * CON: the marketing becomes more complex 
* 30 seconds is a long time to wait for a message! it seems like other factors affected the message delivery time: the age of phones, the quality of service, etc. (Genevieve mentioned that mRelief once did user testing in a basement, and users waited around 30 seconds or so for a message.) CSH does not seem to get great service, which may explain the longer than usual delivery time
* for long messages, find intuitive break points at 160 characters, and send the messages separately. then, if a user needs to wait for the Twilio queue, at least they received some content

**Comment by reginafcompton** [comment]
Co-pilot is free! https://www.twilio.com/copilot

**Comment by reginafcompton** [comment]
We did user testing, again, when CSH did not have the same degree of service issues as it did during our first visit. Users were able to communicate with the app pretty quickly, and so, this confirms Genevieve's suspicion that "something else" (i.e., not Twilio, not our tool, but rather the bad service at CSH) had caused the delays. 

I am closing this issue, since I do not think we have a good case for buying two CSH numbers (which costs more money and, ultimately, would confuse the marketing campaign).
