### ISSUE TITLE
Make survey into interactive narrative

### ISSUE THREAD

**Issue by reginafcompton** [datamade/coordinated-entry-screening#28]
Ben Handy (skilled assessor at Matthew House) suggested "gamifying" the survey.

[Notes on how that might come to fruition.](https://docs.google.com/document/d/1z-P_gjp70LHj_2iGWtfOLC_l3GFm8rLN1RvH4TeplHw/edit)

**Comment by reginafcompton** [comment]
@beamalsky - would love your feedback on the above document

**Comment by reginafcompton** [comment]
n.b. I've been using LucidChart to visualize the decision-tree logic and questions, but I can only export the chart as a PDF, image file, or less-than-helpful csv. It's not a great place for collaborative work, so I was thinking a table embedded in a Google doc makes sense. @beamalsky what software did you use to support storyboarding in game design?

**Comment by beamalsky** [comment]
Love it, I left a couple comments and suggestions on simplifying the language! An easy-to-pick-up and nicely versatile tool for non-linear writing is [Twine](http://twinery.org/). I'd be happy to take a few minutes tomorrow and show you the syntax.

**Comment by reginafcompton** [comment]
I played around with Twine (cool tool!), and put together the beginning of the questionnaire (though the end product is an HTML file, which does not play well with Github). 

Inputting all the questions and various paths to Twine would be tedious, so I just ported everything to a Google spreadsheet: https://docs.google.com/spreadsheets/d/1e5pDtbK0BA_VdznwZggPLlOp9Z9VgpeIowayWDMGYgo/edit#gid=2009216223

**Comment by reginafcompton** [comment]
We are moving forward with B.E.N.! Thanks @beamalsky for your suggestions on this.

**Comment by beamalsky** [comment]
![starwards](https://user-images.githubusercontent.com/1094243/46762566-00ca7480-cc9d-11e8-851a-85655fb6729d.gif)
