### ISSUE TITLE
Improve admin dashboard frontend

### ISSUE THREAD

**Issue by reginafcompton** [datamade/coordinated-entry-screening#50]
The admin dashboard currently uses out-of-the-box styles from Bootstrap and Highcharts. Let's make it look nice!

I'll point to relevant files after I merge https://github.com/datamade/coordinated-entry-screening/pull/49

**Comment by jmithani** [comment]
@reginafcompton would you mind pointing to those files?

**Comment by reginafcompton** [comment]
[Template code](https://github.com/datamade/coordinated-entry-screening/blob/master/templates/ces_admin/ces-dashboard.html) and [CSS](https://github.com/datamade/coordinated-entry-screening/blob/master/coordinated-entry-screening/static/css/custom.css)

[Highcharts helper - requires some custom styles](https://github.com/datamade/coordinated-entry-screening/blob/master/coordinated-entry-screening/static/js/dashboard-charts.js)

**Comment by reginafcompton** [comment]
Closed via https://github.com/datamade/coordinated-entry-screening/pull/54
