### ISSUE TITLE
Create custom icon for B.E.N.

### ISSUE THREAD

**Issue by reginafcompton** [datamade/coordinated-entry-screening#51]
@beamalsky has agreed to contribute her design skills to this project. She will create a simple, but custom icon to represent B.E.N. We need to answer a few questions, before she can get started:

- what are the specs? (colors, size to be displayed, etc.)
- how will the icon be used in the UI?

Given the above, let's determine how much time @beamalsky needs to create the icon and if she has cycles to do it.

**Comment by beamalsky** [comment]
Icon notes:
- Message icon
- Person of color
- Mix of robot and person
- Male-ish
- Circle
- Use CSH colors (https://github.com/datamade/coordinated-entry-screening/issues/55)
- Vector format; save as PNG

**Comment by reginafcompton** [comment]
Closing! Thank you @beamalsky
